name: Mirror and run GitLab CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Mirror + trigger CI
        uses: arash2060/gitlab-mirror-and-ci-action@develop
        with:
          args: "https://gitlab.com/arash2060/commento.git"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "arash2060"
          GITLAB_EMAIL: ${{ secrets.GITLAB_EMAIL }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "19463125"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
