name: Mirror and run GitLab CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/arash2060/commento"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "arash2060"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "commento"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
